[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm run build"

[dev]
  framework = "#static"
  command = "npm run dev"
  port = 8888
  targetPort = 8000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/terms"
  to = "/legal/terms.html"
  status = 301
  force = true

[[redirects]]
  from = "/privacy"
  to = "/legal/privacy.html"
  status = 301
  force = true

[[redirects]]
  from = "/imprint"
  to = "/legal/imprint.html"
  status = 301
  force = true

[[redirects]]
  from = "/aml-policy"
  to = "/legal/aml-policy.html"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    fail_on_score_criteria = [
      "performance=90",
      "accessibility=95"
    ] 