name: Lighthouse CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
      
      - name: Run Lighthouse against static site
        run: |
          lhci autorun --collect.url=http://localhost:8080 \
            --collect.url=http://localhost:8080/sniper-bot.html \
            --collect.url=http://localhost:8080/pricing.html \
            --collect.settings.preset=desktop
      
      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-reports
          path: .lighthouseci
      
      - name: Assert LH scores meet threshold
        run: |
          lhci assert --preset=lighthouse-core/config/default-config.js \
            --assertMatrix='[{"matchingUrlPattern":".*","assertions":{"categories:performance":["error",{"minScore":0.95}],"categories:accessibility":["error",{"minScore":1}],"categories:best-practices":["error",{"minScore":1}],"categories:seo":["error",{"minScore":1}]}}]' 